---
kind: pipeline
type: docker
name: default
image_pull_secrets:
  - nexus_docker
steps:
  - name: Build and push docker
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: repo.isaev.tech/${DRONE_REPO_NAME}
      registry: repo.isaev.tech
      tags:
        - latest
        - ${DRONE_TAG}
  - name: send tg message
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_to
    when:
      status:
        - success
        - failure
